{% set name = "NREL-PySAM-stubs" %}
{% set version = environ.get('VERSION') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
    number: 0
    script:
        - "export PIP_NO_INDEX='False'"
        - "{{ PYTHON }} -m pip install {{name}}=={{version}}"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: https://nrel-pysam.readthedocs.io
  license: BSD 3-Clause
  license_family: BSD
  license_file:
  summary: National Renewable Energy Laboratory's System Advisor Model Python Wrapper, stub files
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - dguittet
